version: "3.8"
services:
  backend:
    build: ./server
    container_name: compyl-server
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
      - kafka
      - zookeeper
    environment:
      PORT: 8000
      NODE_ENV: development
      CONSOLE_LOGS : "true"
      ENCRYPTION_KEY : e8907ce6f646a336bd54a706c32d32a812558e138e9ed44cdc26868db7373c3d
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USERNAME : default
      REDIS_PASSWORD: RadheRadhe
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: compyl
      POSTGRES_PASSWORD: compylpass
      POSTGRES_DB: defaultdb
      KAFKA_BROKER: kafka:9092
    networks:
      - compyl-net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "RadheRadhe"]
    networks:
      - compyl-net

  postgres:
    image: postgres:latest 
    container_name: postgres
    environment:
      POSTGRES_USER: compyl
      POSTGRES_PASSWORD: compylpass
      POSTGRES_DB: defaultdb
    ports:
      - "5432:5432"
    networks:
      - compyl-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - compyl-net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - compyl-net

networks:
  compyl-net:
    driver: bridge
